basePath: /api/v1
definitions:
  base.BaseHttpResponse:
    properties:
      error: {}
      result: {}
      resultcode:
        type: integer
      success:
        type: boolean
      validationErrors:
        items:
          $ref: '#/definitions/validations.ValidationError'
        type: array
    type: object
  dto.GetOtpRequest:
    properties:
      mobileNumber:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - mobileNumber
    type: object
  dto.LoginByMobileNumberRequest:
    properties:
      mobilenumber:
        maxLength: 11
        minLength: 11
        type: string
      otp:
        maxLength: 6
        minLength: 6
        type: string
    required:
    - mobilenumber
    - otp
    type: object
  dto.LoginByUserNameRequest:
    properties:
      mobilenumber:
        maxLength: 120
        minLength: 4
        type: string
      password:
        minLength: 6
        type: string
    required:
    - mobilenumber
    - password
    type: object
  dto.RegisterRequestByUsername:
    properties:
      email:
        minLength: 6
        type: string
      firstname:
        maxLength: 120
        minLength: 4
        type: string
      lastname:
        maxLength: 180
        minLength: 10
        type: string
      password:
        minLength: 6
        type: string
      username:
        maxLength: 120
        minLength: 4
        type: string
    required:
    - firstname
    - password
    - username
    type: object
  handlers.User:
    properties:
      entered_password:
        maxLength: 64
        minLength: 8
        type: string
      first_name:
        maxLength: 80
        minLength: 2
        type: string
      last_name:
        maxLength: 80
        minLength: 2
        type: string
      mobile_number:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - first_name
    - last_name
    type: object
  validations.ValidationError:
    properties:
      message:
        type: string
      property:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
host: localhost:9090
info:
  contact: {}
  description: REST API for Khodro85.
  title: Khodro85 API
  version: "1.0"
paths:
  /health/:
    get:
      description: Health API endpoint
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: Health handler
      tags:
      - Health
  /test/:
    get:
      description: Test API endpoint
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: Test handler
      tags:
      - test
    post:
      consumes:
      - application/json
      description: Test JSON request body binding
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handlers.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.User'
        "400":
          description: Bad Request
          schema: {}
      summary: Test JSON binding
      tags:
      - test
  /user/login-by-mobile/:
    post:
      consumes:
      - application/json
      description: Login to the service by LoginByMobileNumberRequest
      parameters:
      - description: login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginByMobileNumberRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/base.BaseHttpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseHttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/base.BaseHttpResponse'
      summary: Register/Login by User Name
      tags:
      - user
  /user/login-by-username/:
    post:
      consumes:
      - application/json
      description: Login to the service by LoginByUserNameRequest
      parameters:
      - description: login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginByUserNameRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/base.BaseHttpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseHttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/base.BaseHttpResponse'
      summary: Login by User Name
      tags:
      - user
  /user/register-by-username/:
    post:
      consumes:
      - application/json
      description: Login to the service by RegisterRequestByUsername
      parameters:
      - description: login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequestByUsername'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/base.BaseHttpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseHttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/base.BaseHttpResponse'
      summary: Register by User Name
      tags:
      - user
  /user/send-otp/:
    post:
      consumes:
      - application/json
      description: Send OTP code to the user's mobile number
      parameters:
      - description: OTP request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.GetOtpRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/base.BaseHttpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseHttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/base.BaseHttpResponse'
      summary: Send OTP
      tags:
      - user
swagger: "2.0"
